version: "3.5"

volumes:
  mariadb:
   name: mariadb
   driver: local
   driver_opts:
      device: /home/khbouych/data/mariadb
      o : bind
      type : none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
        device: /home/khbouych/data/wordpress
        o : bind
        type : none
networks:
  inception:
   name: inception

services:
  #mariadb
  mariadb:
   image: mariadb
   container_name: mariadb
   build: ./mariadb/.
   volumes:
     - mariadb:/var/lib/mysql
   env_file :
    - .env
   networks :
    - inception
   restart: always
#nginx
  nginx:
    image: nginx
    container_name: nginx
    build: ./nginx/.
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always
#wordpress
  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./wordpress/.
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    env_file :
      - .env
    networks:
      - inception
    restart: always
  #bonus part
  # adminer:
  #   image: adminer
  #   container_name: adminer
  #   build: ./srcs/bonus/adminer/.
  #   depends_on:
  #     - mariadb
  #   ports:
  #     - "600:80"
  #   networks:
  #     - inception
  #   restart: always